openapi: 3.0.0
info:
  title: Denet Test API
  version: 1.0.0
servers:
  - url: /api/v1
    description: API version 1
paths:
  /users/leaderboard:
    get:
      summary: Get leaderboard
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of users on the leaderboard
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Leader'
  /users/{id}/status:
    get:
      summary: Get user status
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The user's status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /users/{id}/task/complete:
    post:
      summary: Mark a task as complete for a user
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostTaskComplete'
      responses:
        '200':
          description: Task marked as complete
  /users/{id}/referrer:
    post:
      summary: Add a referrer for a user
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostReferrer'
      responses:
        '200':
          description: Referrer added
components:
  schemas:
    Leader:
      type: object
      properties:
        ID:
          type: string
        Username:
          type: string
        Email:
          type: string
        Points:
          type: integer
    Status:
      type: object
      properties:
        ID:
          type: string
          format: uuid
        Username:
          type: string
        Email:
          type: string
        Points:
          type: integer
        ReferralCode:
          type: string
        ReferredBy:
          type: string
          format: uuid
        CreatedAt:
          type: string
          format: date-time
    PostTaskComplete:
      type: object
      properties:
        task_type:
          type: string
    PostReferrer:
      type: object
      properties:
        referral_code:
          type: string
        referred_by:
          type: string
          format: uuid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
